name: Mobile

on: [pull_request]

jobs:
  mobile:
    name: Mobile
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Generate Bindings (Android)
        # We must build the Android bindings on Ubuntu,
        # because the macOS used for GitHub Actions contains an outdated NDK version.
        if: matrix.os == 'ubuntu-latest'
        run: |
          go get golang.org/x/mobile/cmd/gomobile
          go install golang.org/x/mobile/cmd/gomobile
          gomobile init
          make bindings-android

      - name: Generate Bindings (iOS)
        if: matrix.os == 'macos-latest'
        # We must unset the ANDROID_HOME and ANDROID_NDK_HOME environment variables,
        # otherwise gomobile tries to generate the bindings for Android.
        #
        # The following is needed to fix the GitHub Action
        # rm -rf /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gomobile-work
        run: |
          unset ANDROID_HOME
          unset ANDROID_NDK_HOME
          go get golang.org/x/mobile/cmd/gomobile
          go install golang.org/x/mobile/cmd/gomobile
          rm -rf /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gomobile-work*
          gomobile init
          make bindings-ios
