name: Mobile

on: [pull_request]

jobs:
  mobile:
    name: Mobile
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Print Environment Information
        shell: bash
        run: |
          echo $PATH
          env
          go env

      - name: Generate Bindings (Android)
        # We must build the Android bindings on Ubuntu,
        # because the macOS used for GitHub Actions contains an outdated NDK version.
        if: matrix.os == 'ubuntu-latest'
        run: |
          go get golang.org/x/mobile/cmd/gomobile
          go install golang.org/x/mobile/cmd/gomobile
          gomobile init
          make bindings-android

      - name: Generate Bindings (iOS)
        if: matrix.os == 'macos-latest'
        # We must unset the ANDROID_HOME and ANDROID_NDK_HOME environment variables,
        # otherwise gomobile tries to generate the bindings for Android.
        run: |
          unset ANDROID_HOME
          unset ANDROID_NDK_HOME
          go get golang.org/x/mobile/cmd/gomobile
          go install golang.org/x/mobile/cmd/gomobile
          gomobile init
          make bindings-ios
